// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: wallet_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_wallet_service_proto protoreflect.FileDescriptor

const file_wallet_service_proto_rawDesc = "" +
	"\n" +
	"\x14wallet_service.proto\x12\x02pb\x1a\x17wallet_add_amount.proto2b\n" +
	"\rWalletService\x12Q\n" +
	"\x10AddAcountbalance\x12\x1c.pb.AddAccountBalanceRequest\x1a\x1d.pb.AddAccountBalanceResponse\"\x00B3Z1github.com/whr129/go-wallet/cmd/wallet-service/pbb\x06proto3"

var file_wallet_service_proto_goTypes = []any{
	(*AddAccountBalanceRequest)(nil),  // 0: pb.AddAccountBalanceRequest
	(*AddAccountBalanceResponse)(nil), // 1: pb.AddAccountBalanceResponse
}
var file_wallet_service_proto_depIdxs = []int32{
	0, // 0: pb.WalletService.AddAcountbalance:input_type -> pb.AddAccountBalanceRequest
	1, // 1: pb.WalletService.AddAcountbalance:output_type -> pb.AddAccountBalanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallet_service_proto_init() }
func file_wallet_service_proto_init() {
	if File_wallet_service_proto != nil {
		return
	}
	file_wallet_add_amount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_service_proto_rawDesc), len(file_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_service_proto_goTypes,
		DependencyIndexes: file_wallet_service_proto_depIdxs,
	}.Build()
	File_wallet_service_proto = out.File
	file_wallet_service_proto_goTypes = nil
	file_wallet_service_proto_depIdxs = nil
}
