// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64       `json:"id"`
	UserID    pgtype.Int8 `json:"user_id"`
	Balance   int64       `json:"balance"`
	Currency  string      `json:"currency"`
	CreatedAt time.Time   `json:"created_at"`
	IsDeleted bool        `json:"is_deleted"`
}
